sudo: false
language: ruby
cache: bundler
notifications:
  email: false

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

script:
  - bundle exec rake test:ci

matrix:
  fast_finish: true
  include:
    - rvm: ruby-head
      gemfile: gemfiles/railsmaster.gemfile
    - rvm: jruby-9.2.8.0
      gemfile: gemfiles/jruby.gemfile
    - rvm: 2.6.5
      gemfile: gemfiles/rails6.gemfile
    - rvm: 2.5.3
      gemfile: Gemfile
    - rvm: 2.5.3
      gemfile: gemfiles/rails42.gemfile
  allow_failures:
    - rvm: ruby-head
      gemfile: gemfiles/railsmaster.gemfile
    - rvm: jruby-9.2.8.0
      gemfile: gemfiles/jruby.gemfile
